### ISSUE TITLE
Rendering problems in chrome

### ISSUE THREAD

**Issue by szarnekow** [JanKoehnlein/XRobot#44]
Version 40.0.2188.2 dev (64-bit)

![screen shot 2014-10-16 at 16 30 45](https://cloud.githubusercontent.com/assets/375492/4664107/4794b66e-5541-11e4-8b18-cbba88c2fc9b.png)

Line numbers and the actual rendering in the widget is out of sync.

Encoding auto-detect / ISO-8859-1
Font size: medium
Standard fonts: times, courier, helvetica

**Comment by JanKoehnlein** [comment]
🤖
